### ISSUE TITLE
Compilation warning (version 2.1.4)

### ISSUE THREAD

**Issue by seralexwin** [WickyNilliams/enquire.js#160]
Line 7 of "dist/enquire.js" contains minified js code.  I'm using create-react-app template and my app compiled with warning about this line of code.

**Comment by WickyNilliams** [comment]
Why does that cause a warning?

**Comment by seralexwin** [comment]
Because you include minified js code inside not minified version of enquire.js

**Comment by WickyNilliams** [comment]
It's a bizarre thing to complain about. It shouldn't cause any issues
having a line of minified code, it's simply the browserify boilerplate.

What is the exact message? Is there anywhere in CRA docs that mentions this
behaviour?

On 8 Mar 2017 8:37 pm, "seralexwin" <notifications@github.com> wrote:

Because you include minified js code inside not minified version of
enquire.js

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/WickyNilliams/enquire.js/issues/160#issuecomment-285161417>,
or mute the thread

**Comment by szeller** [comment]
I'm assuming that this is a similar problem if not 100% the same.  During our browerify run, I'm seeing the following.

```
[14:55:08] Starting 'js'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '1' from '/Users/szeller/dev/foo/node_modules/react-slick/node_modules/react-responsive-mixin/node_modules/enquire.js/dist'
```

**Comment by WickyNilliams** [comment]
OK how about this... I point the main field of package.json to `src/index.js` and create a separate UMD build for people that want to consume it that way. That should do the trick, right?

**Comment by szeller** [comment]
yeah, my guess is that will work fine.

**Comment by WickyNilliams** [comment]
I just did that and published as `v2.1.5`. I also deprecated `v2.1.4` on npm. Please try and report back

**Comment by szeller** [comment]
yep.  that fixed the problem I was having.

**Comment by WickyNilliams** [comment]
Awesome! @seralexwin how about for you?

**Comment by seralexwin** [comment]
I can't reproduce it anymore

**Comment by WickyNilliams** [comment]
Good to hear!
